### ISSUE TITLE
Không vào login thủ công được sau khi tải

### ISSUE THREAD

**Issue by SMUEric1127** [pk9r327/Dragonboy#77]
Mình clone và build lại mọi thứ, nhưng mà start game bằng tay thì không được, chỉ có qua qltk mới được, cho mình hỏi cách set tay ntn ad nhỉ

**Comment by pk9r327** [comment]
Hướng ban đầu mình phát triển dự án này là mình chỉ cho mở game và đăng nhập qua QLTK rồi, khi game bằng quản lý tài khoản nó sẽ có một port để kết nối tcp socket với QLTK sau đó nhận thông tin về tài khoản, mật khẩu, server, ... rồi tự đăng nhập. Bạn mở game thủ công thì sẽ không kết nối được với QLTK nên quá trình đăng nhập không có thông tin và xảy ra lỗi.

**Comment by pk9r327** [comment]
Bạn có thể xem qua một số đoạn sau để sửa lại, còn mình không hỗ trợ khởi động game không qua QLTK trong dự án này nha.

Vào Mod/GameEvents.cs
- `onGameStarted` -> `SocketClient.gI.initSender()`: Hàm này tạo kết nối socket tcp, nhận thông tin đăng nhập.
- `onServerListScreenLoaded`: Hàm này để tự động đăng nhập.
- `onLogin`: Hàm này sử dụng thông tin đăng nhập.
- `onGetRMSPath`: Hàm này sử dụng thông tin server.
