### ISSUE TITLE
Command hanlders doesnt work

### ISSUE THREAD

**Issue by EdwardLTC** [pk9r327/Dragonboy#99]
hi team, mình check code thấy hình như các  ChatCommandHandler và HotkeyCommandHandler, không được khởi tạo, nên nó không work, mình muốn sửa cho nó work thì mình phải init vào chỗ nào nhỉ?

**Comment by ElectroHeavenVN** [comment]
Bạn có thể xem code cũ (trước khi project được chuyển sang dự án Unity) tại [branch legacy](../tree/legacy) để tham khảo nhé
